# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jo}
  s.version = "0.17.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Phung Le Son"]
  s.date = %q{2011-04-14}
  s.description = %q{A concise and easy-to-use Ruby library to put json data into SQL column.}
  s.email = %q{leson.phung@gmail.com}
  s.files = [
    "lib/jo.rb",
    "lib/jo/active_record.rb",
    "lib/jo/array.rb",
    "lib/jo/base.rb",
    "lib/jo/convert.rb",
    "lib/jo/dirty.rb",
    "lib/jo/hash.rb",
    "lib/jo/helper.rb",
    "lib/jo/locale.rb",
    "lib/jo/meta.rb",
    "lib/jo/polymorphism.rb",
    "lib/jo/validations.rb",
    "tasks/cucumber.rb",
    "tasks/distribution.rb"
  ]
  s.homepage = %q{http://twitter.com/phungleson}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{ActiveRecord/Rails Jo library}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
  end
end

